import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '~/styles/Home.module.css';
import Text from '~/components/Text';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
        <Text size="50px">This text is sample</Text>
      </main>
    </div>
  );
};

export default Home;
